api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "cc-payment-eligibility"
type = "function"
uid = "e30606b6-cb46-7e6a-7dd0-321109e4a5983e25b887"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
